version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ${{ parameters.name }}
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ${{ parameters.name }}
    ports:
      - "5432:5432"
